### ISSUE TITLE
Sugerencias sobre traducciones.

### ISSUE THREAD

**Issue by mpijierro** [Laraveles/translation-rules#2]
Hola,
abro este issue para dejar algunas sugerencias para las traducciones. Una vez debatidas las que creamos convenientes, si las hubiera, las pasamos al documento oficial.

1) Después de pensar un rato, al final, en mi opinión no debería traducirse nada de código, salvo en el caso de los comentarios. Es decir, no traducir ni variables, ni nombres de métodos ni de clases ni nada, el código debería ser intocable y no modificarlo nosotros, por lo tanto, dejarlo en inglés. De esta forma, además, evitamos que algunas partes de código estén traducidas y otras no, dependiendo de la persona que traduzca y de lo que pueda pensar si es necesario traducir o no.

2) A raíz de una pregunta que lancé en el foro sobre que hacer con palabras técnicas de Laravel como: 'binding', 'middelware', 'listeners', 'routers'... Israel comentó que se dejaran tal cual y crearamos una wiki o un pequeño diccionario con el significado de cada una. A mi me parece bien las dos cosas. Dejarlas en inglés y explicarlas por otro lado. Lo que si habría que llegar es a un acuerdo sobre que palabras pertenecen a este grupo, cuales merece la pena traducir y cuáles dejar en su forma nativa y llevar al diccionario.

3) Otra duda: ¿Traducir literalmente cada frase dándole un sentido en español lógicamente?, ¿o darnos la libertad de introducir algo más de texto en una traducción para que algo quede mejor explicado?. Es que ahora no se me ocurre ningún ejemplo :p así que no sé si me he explicado bien.

4) Buscando estándares de traducciones de otras plataformas/framewoks, encontré la de symfony la cual deja algunos puntos interesantes pero tampoco entra mucho en profundidad: http://symfony.com/doc/current/contributing/documentation/standards.html

(Dejo literal un par de anotaciones sobre como documentar ficheros y directorios)

1)  Files and Directories

* When referencing directories, always add a trailing slash to avoid confusions with regular files (e.g. "execute the console script located at the app/ directory").

* When referencing file extensions explicitly, you should include a leading dot for every extension (e.g. "XML files use the .xml extension").

Eso es todo de momento.
Un saludo.

**Comment by IsraelOrtuno** [comment]
Estoy investigando por que symfony está traduciendo su documentación a italiano utilizando GitHub, y eso puede ser muy interesante.
